// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TaskManagement.Infrastructure.Persistence;

#nullable disable

namespace TaskManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<Guid>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<int>("Priority").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Tasks");
            });

            modelBuilder.Entity("TaskManagement.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<Guid>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
            {
                b.HasOne("TaskManagement.Domain.Entities.User", "User")
                    .WithMany("Tasks")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("TaskManagement.Domain.Entities.User", b =>
            {
                b.Navigation("Tasks");
            });
#pragma warning restore 612, 618
        }
    }
}